import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig, type DefaultTheme } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

// The platform documentation sidebar is generated by
// scripts/sync-platform-docs.mjs (run in CI before the build; run it locally
// against a platform checkout to preview the synced docs). Absent means the
// sync has not run - the site still builds, without the platform section.
const platformSidebarPath = fileURLToPath(
  new URL("./generated/platform-sidebar.json", import.meta.url),
);
const platformSidebar: DefaultTheme.SidebarItem[] = existsSync(platformSidebarPath)
  ? JSON.parse(readFileSync(platformSidebarPath, "utf8"))
  : [];

const siteTitle = "Hegemony";
const browserTitle = "Hegemony.sh";
const githubRepoUrl = "https://github.com/hegemony-sh/Hegemony";
const descriptionEn =
  "A proof-of-execution platform for deterministic, long-running infrastructure workflows on Temporal.";
const descriptionCs =
  "Platforma proof-of-execution pro deterministická, dlouhotrvající infrastrukturní workflow postavená na Temporal.";

// https://vitepress.dev/reference/site-config
export default withMermaid(
  defineConfig({
    srcExclude: ["README.md", "test-results/**", ".platform/**"],
    // /docs/platform/ pages exist only after the sync script has run; the
    // built-HTML link check in CI verifies them strictly there.
    ignoreDeadLinks: [
      /^\/docs\/platform\//,
      // Example/default URLs in the synced reference pages (settings defaults
      // like the local Keycloak issuer) are illustrations, not links to check.
      /^https?:\/\/(localhost|127\.0\.0\.1)/,
    ],

    // mermaid lazy-loads its diagram renderers, so the dev server's dependency
    // scan misses their CommonJS imports (fastdom in particular has no ESM
    // default export until Vite pre-bundles it, which breaks every page in dev
    // mode and the e2e suite with it). Force both through optimization;
    // withMermaid appends its own additions to this list. Production builds
    // are unaffected either way (rollup does CJS interop itself).
    vite: {
      optimizeDeps: {
        include: ["mermaid", "fastdom"],
      },
    },

    markdown: {
      anchor: {
        // GitHub's slug algorithm, so anchors written against GitHub rendering
        // (the platform docs' native habitat, verified by its link gate) hit
        // the same ids here: "Flow / Flow Definition" -> #flow--flow-definition.
        slugify: (value: string) =>
          value
            .normalize("NFKD")
            .replace(/[\u0300-\u036f]/g, "")
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9 _-]/g, "")
            .replace(/ /g, "-"),
      },
      config(md) {
        // The platform docs show template syntax ({{ vars.X }}) in inline code
        // spans. VitePress v-pres fenced code automatically but not inline
        // code, so Vue would parse those mustaches as interpolations and fail
        // the build; mark every inline code span v-pre.
        const defaultRender =
          md.renderer.rules.code_inline ??
          ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));
        md.renderer.rules.code_inline = (tokens, idx, options, env, self) => {
          tokens[idx].attrSet("v-pre", "");
          return defaultRender(tokens, idx, options, env, self);
        };
      },
    },
    title: browserTitle,
    titleTemplate: ":title - Hegemony.sh",
    description: descriptionEn,
    lang: "en-US",
    cleanUrls: true,
    appearance: "dark",

    head: [
      ["link", { rel: "icon", href: "/favicon.ico", sizes: "any" }],
      ["link", { rel: "icon", type: "image/png", sizes: "32x32", href: "/brand/favicon-32.png" }],
      ["link", { rel: "icon", type: "image/png", sizes: "16x16", href: "/brand/favicon-16.png" }],
      ["link", { rel: "apple-touch-icon", href: "/brand/apple-touch-icon.png" }],
      ["link", { rel: "manifest", href: "/site.webmanifest" }],
      ["meta", { name: "theme-color", content: "#131313" }],
      ["meta", { property: "og:type", content: "website" }],
      ["meta", { property: "og:title", content: browserTitle }],
      ["meta", { property: "og:description", content: descriptionEn }],
      ["meta", { property: "og:url", content: "https://hegemony.sh/" }],
      ["meta", { property: "og:image", content: "https://hegemony.sh/brand/logo-stacked@2x.png" }],
    ],

    themeConfig: {
      logo: "/brand/favicon-48.png",
      siteTitle,
      socialLinks: [{ icon: "github", link: githubRepoUrl, ariaLabel: "GitHub" }],

      search: {
        provider: "local",
        options: {
          locales: {
            cs: {
              translations: {
                button: {
                  buttonText: "Hledat",
                  buttonAriaLabel: "Otevřít vyhledávání",
                },
                modal: {
                  displayDetails: "Zobrazit podrobný seznam",
                  resetButtonTitle: "Vymazat hledání",
                  backButtonTitle: "Zavřít vyhledávání",
                  noResultsText: "Nenalezeny žádné výsledky pro",
                  footer: {
                    selectText: "pro výběr",
                    selectKeyAriaLabel: "Enter",
                    navigateText: "pro pohyb",
                    navigateUpKeyAriaLabel: "šipka nahoru",
                    navigateDownKeyAriaLabel: "šipka dolů",
                    closeText: "pro zavření",
                    closeKeyAriaLabel: "Escape",
                  },
                },
              },
            },
          },
        },
      },
    },

    locales: {
      root: {
        label: "English",
        lang: "en-US",
        title: browserTitle,
        description: descriptionEn,
        themeConfig: {
          nav: [
            { text: "Home", link: "/" },
            { text: "Docs", link: "/docs/" },
            { text: "API Reference", link: "/api/", target: "_self" },
          ],
          sidebar: {
            "/docs/": [
              {
                text: "Getting Started",
                items: [{ text: "Introduction", link: "/docs/" }],
              },
              ...(platformSidebar.length > 0
                ? [
                    {
                      text: "Platform Documentation",
                      items: [{ text: "Browse the platform docs", link: "/docs/platform/" }],
                    },
                  ]
                : []),
            ],
            "/docs/platform/": platformSidebar,
          },
          langMenuLabel: "Languages",
          footer: {
            message:
              'Released as open source under the AGPL-3.0-or-later license. Development is sponsored by <a href="https://rexonix.cz/" target="_blank" rel="noreferrer">Rexonix s.r.o.</a>. Commercial licensing is available — <a href="mailto:contact@hegemony.sh">contact@hegemony.sh</a>.',
            copyright: "Copyright © 2025–2026 Jakub Trávník",
          },
        },
      },
      cs: {
        label: "Čeština",
        lang: "cs-CZ",
        link: "/cs/",
        title: browserTitle,
        description: descriptionCs,
        themeConfig: {
          nav: [
            { text: "Úvod", link: "/cs/" },
            { text: "Dokumentace", link: "/cs/docs/" },
          ],
          sidebar: {
            "/cs/docs/": [
              {
                text: "První kroky",
                items: [{ text: "Úvod", link: "/cs/docs/" }],
              },
            ],
          },
          langMenuLabel: "Jazyky",
          footer: {
            message:
              'Open source projekt pod licencí AGPL-3.0-or-later. Vývoj projektu finančně podporuje <a href="https://rexonix.cz/" target="_blank" rel="noreferrer">Rexonix s.r.o.</a>. K dispozici je i komerční licence — <a href="mailto:contact@hegemony.sh">contact@hegemony.sh</a>.',
            copyright: "Copyright © 2025–2026 Jakub Trávník",
          },
        },
      },
    },
  }),
);
